# Generated by Django 5.0.4 on 2024-04-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_completedtask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedtask',
            name='CompletedTask',
        ),
        migrations.AddField(
            model_name='completedtask',
            name='completed_task',
            field=models.CharField(default='Null', max_length=500),
            preserve_default=False,
        ),
    ]
