# Generated by Django 5.0.4 on 2024-04-17 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_remove_completedtask_completedtask_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completedtask',
            old_name='completed_task',
            new_name='task',
        ),
    ]
