# Generated by Django 5.0.4 on 2024-09-14 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_rename_completed_task_completedtask_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completedtask',
            old_name='task',
            new_name='completed_task',
        ),
    ]
